version: '3.9' #version

services:
  backend:
    container_name: duSOC_Backend_Container
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "./start_server.sh"]
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app  # Optional: for live sync with host

  # db:
  #   container_name: duSOC_Postgres_Container
  #   image: postgres:16
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - dusocportal_backend_dusocportal_backend_postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 10s
  #     timeout: 5s

  redis:
    container_name: duSOC_Redis_Container
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: duSOC_RabbitMQ_Container
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    container_name: duSOC_Celery_Container
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "sockportal__backend", "worker", "--loglevel=info"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    volumes:
      - .:/app  # Optional: for live sync with host
    environment:
      - C_FORCE_ROOT=true  # Allows Celery to run as root in the container (optional, use with caution)

  celery-beat:
    container_name: duSOC_Celery_Beat_Container
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "sockportal__backend",  "beat", "--loglevel=info"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true

volumes:
  # dusocportal_backend_dusocportal_backend_postgres_data:
  redis_data:
  rabbitmq_data:
